name: Run Python Script

on:
  push:
    branches:
      - main  #triggers on pushes to the main branch
  workflow_dispatch:  #allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  #gitHub's default Linux environment which is in Ubuntu for this one

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  #checks out your repository's code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  #use the same Python version as locally

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run Python Script
        run: python datascript.py

      - name: Upload Report
        uses: actions/upload-artifact@v4 #upload files(artifacts) created duyring workflow
        with:
          name: report
          path: report.txt  #uploads report.txt as an artifact
