# .github/workflows/main.yml

name: System Monitoring Workflow

on: 
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  metrics_monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psutil
      - name: Run disk monitor script
        run: python disk_monitor.py

  upload_logs:
    runs-on: ubuntu-latest
    needs: [metrics_monitor]
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Upload system logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            system_metrics.log
            disk_usage.log
