name: Monitor Script Workflow

on:
  push:
      branches:
        -main

jobs:
  run-monitor-script:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3 #checkout repo code

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
          python-version: '3.12' # use same python version as locally

     - name: Install dependencies
       run: |
          pip install psutil
     - name: Run Monitor Script
       run:  | 
         python monitorscript.py

     - name: Upload Output Artifact
       uses: actions/upload-artifact@v4
       with:
        name: monitor-output
        path: output.txt


